<?php

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

function update(array &$form, FormStateInterface $form_state)
{
  $node = Node::load($form_state->getValue('title'));
  if($form_state->getValue('status') === 'published'){
    $node->setPublished();
  } else {
    $node->setUnpublished();
  }
  if($form_state->getValue('sticky') === 'sticky'){
    $node->setSticky(true);
  } else {
    $node->setSticky(false);
  }
  $node->save();
}

function delete(array &$form, FormStateInterface $form_state)
{
  $node = Node::load($form_state->getValue('title'));
  $node->delete();
}

function drupal_test_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\Core\Database\Connection $connection */
  $connection = \Drupal::service('database');
  $connection->insert('drupal_test')->fields(array(
    'nid' => 1,
    'uid' => 1,
    'totalcount' => 1,
    'daycount' => 1,
    'timestamp' => \Drupal::time()->getRequestTime()
  ))->execute();
//  $build['body'][0]['stats'] = [
//    '#markup' => '<div class="asd">qweqwe</div>'
//  ];
}
